// Country enum matching backend API
export const COUNTRIES = [
  { id: "1", name: { en: "Afghanistan", tr: "Afganistan", fr: "Afghanistan" } },
  { id: "2", name: { en: "Albania", tr: "Arnavutluk", fr: "Albanie" } },
  { id: "3", name: { en: "Algeria", tr: "Cezayir", fr: "Algérie" } },
  { id: "4", name: { en: "Andorra", tr: "Andorra", fr: "Andorre" } },
  { id: "5", name: { en: "Angola", tr: "Angola", fr: "Angola" } },
  { id: "6", name: { en: "Antigua and Barbuda", tr: "Antigua ve Barbuda", fr: "Antigua-et-Barbuda" } },
  { id: "7", name: { en: "Argentina", tr: "Arjantin", fr: "Argentine" } },
  { id: "8", name: { en: "Armenia", tr: "Ermenistan", fr: "Arménie" } },
  { id: "9", name: { en: "Australia", tr: "Avustralya", fr: "Australie" } },
  { id: "10", name: { en: "Austria", tr: "Avusturya", fr: "Autriche" } },
  { id: "11", name: { en: "Azerbaijan", tr: "Azerbaycan", fr: "Azerbaïdjan" } },
  { id: "12", name: { en: "Bahamas", tr: "Bahamalar", fr: "Bahamas" } },
  { id: "13", name: { en: "Bahrain", tr: "Bahreyn", fr: "Bahreïn" } },
  { id: "14", name: { en: "Bangladesh", tr: "Bangladeş", fr: "Bangladesh" } },
  { id: "15", name: { en: "Barbados", tr: "Barbados", fr: "Barbade" } },
  { id: "16", name: { en: "Belarus", tr: "Beyaz Rusya", fr: "Biélorussie" } },
  { id: "17", name: { en: "Belgium", tr: "Belçika", fr: "Belgique" } },
  { id: "18", name: { en: "Belize", tr: "Belize", fr: "Belize" } },
  { id: "19", name: { en: "Benin", tr: "Benin", fr: "Bénin" } },
  { id: "20", name: { en: "Bhutan", tr: "Butan", fr: "Bhoutan" } },
  { id: "21", name: { en: "Bolivia", tr: "Bolivya", fr: "Bolivie" } },
  { id: "22", name: { en: "Bosnia and Herzegovina", tr: "Bosna-Hersek", fr: "Bosnie-Herzégovine" } },
  { id: "23", name: { en: "Botswana", tr: "Botsvana", fr: "Botswana" } },
  { id: "24", name: { en: "Brazil", tr: "Brezilya", fr: "Brésil" } },
  { id: "25", name: { en: "Brunei", tr: "Brunei", fr: "Brunei" } },
  { id: "26", name: { en: "Bulgaria", tr: "Bulgaristan", fr: "Bulgarie" } },
  { id: "27", name: { en: "Burkina Faso", tr: "Burkina Faso", fr: "Burkina Faso" } },
  { id: "28", name: { en: "Burundi", tr: "Burundi", fr: "Burundi" } },
  { id: "29", name: { en: "Cabo Verde", tr: "Yeşil Burun Adaları", fr: "Cap-Vert" } },
  { id: "30", name: { en: "Cambodia", tr: "Kamboçya", fr: "Cambodge" } },
  { id: "31", name: { en: "Cameroon", tr: "Kamerun", fr: "Cameroun" } },
  { id: "32", name: { en: "Canada", tr: "Kanada", fr: "Canada" } },
  { id: "33", name: { en: "Central African Republic", tr: "Orta Afrika Cumhuriyeti", fr: "République centrafricaine" } },
  { id: "34", name: { en: "Chad", tr: "Çad", fr: "Tchad" } },
  { id: "35", name: { en: "Chile", tr: "Şili", fr: "Chili" } },
  { id: "36", name: { en: "China", tr: "Çin", fr: "Chine" } },
  { id: "37", name: { en: "Colombia", tr: "Kolombiya", fr: "Colombie" } },
  { id: "38", name: { en: "Comoros", tr: "Komorlar", fr: "Comores" } },
  { id: "39", name: { en: "Congo (DRC)", tr: "Kongo Demokratik Cumhuriyeti", fr: "Congo (RDC)" } },
  { id: "40", name: { en: "Congo (Republic)", tr: "Kongo Cumhuriyeti", fr: "Congo (République)" } },
  { id: "41", name: { en: "Costa Rica", tr: "Kosta Rika", fr: "Costa Rica" } },
  { id: "42", name: { en: "Croatia", tr: "Hırvatistan", fr: "Croatie" } },
  { id: "43", name: { en: "Cuba", tr: "Küba", fr: "Cuba" } },
  { id: "44", name: { en: "Cyprus", tr: "Kıbrıs", fr: "Chypre" } },
  { id: "45", name: { en: "Czech Republic", tr: "Çek Cumhuriyeti", fr: "République tchèque" } },
  { id: "46", name: { en: "Denmark", tr: "Danimarka", fr: "Danemark" } },
  { id: "47", name: { en: "Djibouti", tr: "Cibuti", fr: "Djibouti" } },
  { id: "48", name: { en: "Dominica", tr: "Dominika", fr: "Dominique" } },
  { id: "49", name: { en: "Dominican Republic", tr: "Dominik Cumhuriyeti", fr: "République dominicaine" } },
  { id: "50", name: { en: "East Timor", tr: "Doğu Timor", fr: "Timor oriental" } },
  { id: "51", name: { en: "Ecuador", tr: "Ekvador", fr: "Équateur" } },
  { id: "52", name: { en: "Egypt", tr: "Mısır", fr: "Égypte" } },
  { id: "53", name: { en: "El Salvador", tr: "El Salvador", fr: "Salvador" } },
  { id: "54", name: { en: "Equatorial Guinea", tr: "Ekvator Ginesi", fr: "Guinée équatoriale" } },
  { id: "55", name: { en: "Eritrea", tr: "Eritre", fr: "Érythrée" } },
  { id: "56", name: { en: "Estonia", tr: "Estonya", fr: "Estonie" } },
  { id: "57", name: { en: "Eswatini", tr: "Esvatini", fr: "Eswatini" } },
  { id: "58", name: { en: "Ethiopia", tr: "Etiyopya", fr: "Éthiopie" } },
  { id: "59", name: { en: "Fiji", tr: "Fiji", fr: "Fidji" } },
  { id: "60", name: { en: "Finland", tr: "Finlandiya", fr: "Finlande" } },
  { id: "61", name: { en: "France", tr: "Fransa", fr: "France" } },
  { id: "62", name: { en: "Gabon", tr: "Gabon", fr: "Gabon" } },
  { id: "63", name: { en: "Gambia", tr: "Gambiya", fr: "Gambie" } },
  { id: "64", name: { en: "Georgia", tr: "Gürcistan", fr: "Géorgie" } },
  { id: "65", name: { en: "Germany", tr: "Almanya", fr: "Allemagne" } },
  { id: "66", name: { en: "Ghana", tr: "Gana", fr: "Ghana" } },
  { id: "67", name: { en: "Greece", tr: "Yunanistan", fr: "Grèce" } },
  { id: "68", name: { en: "Grenada", tr: "Grenada", fr: "Grenade" } },
  { id: "69", name: { en: "Guatemala", tr: "Guatemala", fr: "Guatemala" } },
  { id: "70", name: { en: "Guinea", tr: "Gine", fr: "Guinée" } },
  { id: "71", name: { en: "Guinea-Bissau", tr: "Gine-Bissau", fr: "Guinée-Bissau" } },
  { id: "72", name: { en: "Guyana", tr: "Guyana", fr: "Guyana" } },
  { id: "73", name: { en: "Haiti", tr: "Haiti", fr: "Haïti" } },
  { id: "74", name: { en: "Honduras", tr: "Honduras", fr: "Honduras" } },
  { id: "75", name: { en: "Hungary", tr: "Macaristan", fr: "Hongrie" } },
  { id: "76", name: { en: "Iceland", tr: "İzlanda", fr: "Islande" } },
  { id: "77", name: { en: "India", tr: "Hindistan", fr: "Inde" } },
  { id: "78", name: { en: "Indonesia", tr: "Endonezya", fr: "Indonésie" } },
  { id: "79", name: { en: "Iran", tr: "İran", fr: "Iran" } },
  { id: "80", name: { en: "Iraq", tr: "Irak", fr: "Irak" } },
  { id: "81", name: { en: "Ireland", tr: "İrlanda", fr: "Irlande" } },
  { id: "82", name: { en: "Israel", tr: "İsrail", fr: "Israël" } },
  { id: "83", name: { en: "Italy", tr: "İtalya", fr: "Italie" } },
  { id: "84", name: { en: "Ivory Coast", tr: "Fildişi Sahili", fr: "Côte d'Ivoire" } },
  { id: "85", name: { en: "Jamaica", tr: "Jamaika", fr: "Jamaïque" } },
  { id: "86", name: { en: "Japan", tr: "Japonya", fr: "Japon" } },
  { id: "87", name: { en: "Jordan", tr: "Ürdün", fr: "Jordanie" } },
  { id: "88", name: { en: "Kazakhstan", tr: "Kazakistan", fr: "Kazakhstan" } },
  { id: "89", name: { en: "Kenya", tr: "Kenya", fr: "Kenya" } },
  { id: "90", name: { en: "Kiribati", tr: "Kiribati", fr: "Kiribati" } },
  { id: "91", name: { en: "Kosovo", tr: "Kosova", fr: "Kosovo" } },
  { id: "92", name: { en: "Kuwait", tr: "Kuveyt", fr: "Koweït" } },
  { id: "93", name: { en: "Kyrgyzstan", tr: "Kırgızistan", fr: "Kirghizistan" } },
  { id: "94", name: { en: "Laos", tr: "Laos", fr: "Laos" } },
  { id: "95", name: { en: "Latvia", tr: "Letonya", fr: "Lettonie" } },
  { id: "96", name: { en: "Lebanon", tr: "Lübnan", fr: "Liban" } },
  { id: "97", name: { en: "Lesotho", tr: "Lesotho", fr: "Lesotho" } },
  { id: "98", name: { en: "Liberia", tr: "Liberya", fr: "Liberia" } },
  { id: "99", name: { en: "Libya", tr: "Libya", fr: "Libye" } },
  { id: "100", name: { en: "Liechtenstein", tr: "Lihtenştayn", fr: "Liechtenstein" } },
  { id: "101", name: { en: "Lithuania", tr: "Litvanya", fr: "Lituanie" } },
  { id: "102", name: { en: "Luxembourg", tr: "Lüksemburg", fr: "Luxembourg" } },
  { id: "103", name: { en: "Madagascar", tr: "Madagaskar", fr: "Madagascar" } },
  { id: "104", name: { en: "Malawi", tr: "Malavi", fr: "Malawi" } },
  { id: "105", name: { en: "Malaysia", tr: "Malezya", fr: "Malaisie" } },
  { id: "106", name: { en: "Maldives", tr: "Maldivler", fr: "Maldives" } },
  { id: "107", name: { en: "Mali", tr: "Mali", fr: "Mali" } },
  { id: "108", name: { en: "Malta", tr: "Malta", fr: "Malte" } },
  { id: "109", name: { en: "Marshall Islands", tr: "Marshall Adaları", fr: "Îles Marshall" } },
  { id: "110", name: { en: "Mauritania", tr: "Moritanya", fr: "Mauritanie" } },
  { id: "111", name: { en: "Mauritius", tr: "Mauritius", fr: "Maurice" } },
  { id: "112", name: { en: "Mexico", tr: "Meksika", fr: "Mexique" } },
  { id: "113", name: { en: "Micronesia", tr: "Mikronezya", fr: "Micronésie" } },
  { id: "114", name: { en: "Moldova", tr: "Moldova", fr: "Moldavie" } },
  { id: "115", name: { en: "Monaco", tr: "Monako", fr: "Monaco" } },
  { id: "116", name: { en: "Mongolia", tr: "Moğolistan", fr: "Mongolie" } },
  { id: "117", name: { en: "Montenegro", tr: "Karadağ", fr: "Monténégro" } },
  { id: "118", name: { en: "Morocco", tr: "Fas", fr: "Maroc" } },
  { id: "119", name: { en: "Mozambique", tr: "Mozambik", fr: "Mozambique" } },
  { id: "120", name: { en: "Myanmar", tr: "Myanmar", fr: "Myanmar" } },
  { id: "121", name: { en: "Namibia", tr: "Namibya", fr: "Namibie" } },
  { id: "122", name: { en: "Nauru", tr: "Nauru", fr: "Nauru" } },
  { id: "123", name: { en: "Nepal", tr: "Nepal", fr: "Népal" } },
  { id: "124", name: { en: "Netherlands", tr: "Hollanda", fr: "Pays-Bas" } },
  { id: "125", name: { en: "New Zealand", tr: "Yeni Zelanda", fr: "Nouvelle-Zélande" } },
  { id: "126", name: { en: "Nicaragua", tr: "Nikaragua", fr: "Nicaragua" } },
  { id: "127", name: { en: "Niger", tr: "Nijer", fr: "Niger" } },
  { id: "128", name: { en: "Nigeria", tr: "Nijerya", fr: "Nigéria" } },
  { id: "129", name: { en: "North Korea", tr: "Kuzey Kore", fr: "Corée du Nord" } },
  { id: "130", name: { en: "North Macedonia", tr: "Kuzey Makedonya", fr: "Macédoine du Nord" } },
  { id: "131", name: { en: "Norway", tr: "Norveç", fr: "Norvège" } },
  { id: "132", name: { en: "Oman", tr: "Umman", fr: "Oman" } },
  { id: "133", name: { en: "Pakistan", tr: "Pakistan", fr: "Pakistan" } },
  { id: "134", name: { en: "Palau", tr: "Palau", fr: "Palaos" } },
  { id: "135", name: { en: "Palestine", tr: "Filistin", fr: "Palestine" } },
  { id: "136", name: { en: "Panama", tr: "Panama", fr: "Panama" } },
  { id: "137", name: { en: "Papua New Guinea", tr: "Papua Yeni Gine", fr: "Papouasie-Nouvelle-Guinée" } },
  { id: "138", name: { en: "Paraguay", tr: "Paraguay", fr: "Paraguay" } },
  { id: "139", name: { en: "Peru", tr: "Peru", fr: "Pérou" } },
  { id: "140", name: { en: "Philippines", tr: "Filipinler", fr: "Philippines" } },
  { id: "141", name: { en: "Poland", tr: "Polonya", fr: "Pologne" } },
  { id: "142", name: { en: "Portugal", tr: "Portekiz", fr: "Portugal" } },
  { id: "143", name: { en: "Qatar", tr: "Katar", fr: "Qatar" } },
  { id: "144", name: { en: "Romania", tr: "Romanya", fr: "Roumanie" } },
  { id: "145", name: { en: "Russia", tr: "Rusya", fr: "Russie" } },
  { id: "146", name: { en: "Rwanda", tr: "Ruanda", fr: "Rwanda" } },
  { id: "147", name: { en: "Saint Kitts and Nevis", tr: "Saint Kitts ve Nevis", fr: "Saint-Kitts-et-Nevis" } },
  { id: "148", name: { en: "Saint Lucia", tr: "Saint Lucia", fr: "Sainte-Lucie" } },
  { id: "149", name: { en: "Saint Vincent and the Grenadines", tr: "Saint Vincent ve Grenadinler", fr: "Saint-Vincent-et-les-Grenadines" } },
  { id: "150", name: { en: "Samoa", tr: "Samoa", fr: "Samoa" } },
  { id: "151", name: { en: "San Marino", tr: "San Marino", fr: "Saint-Marin" } },
  { id: "152", name: { en: "Sao Tome and Principe", tr: "Sao Tome ve Principe", fr: "Sao Tomé-et-Principe" } },
  { id: "153", name: { en: "Saudi Arabia", tr: "Suudi Arabistan", fr: "Arabie saoudite" } },
  { id: "154", name: { en: "Senegal", tr: "Senegal", fr: "Sénégal" } },
  { id: "155", name: { en: "Serbia", tr: "Sırbistan", fr: "Serbie" } },
  { id: "156", name: { en: "Seychelles", tr: "Seyşeller", fr: "Seychelles" } },
  { id: "157", name: { en: "Sierra Leone", tr: "Sierra Leone", fr: "Sierra Leone" } },
  { id: "158", name: { en: "Singapore", tr: "Singapur", fr: "Singapour" } },
  { id: "159", name: { en: "Slovakia", tr: "Slovakya", fr: "Slovaquie" } },
  { id: "160", name: { en: "Slovenia", tr: "Slovenya", fr: "Slovénie" } },
  { id: "161", name: { en: "Solomon Islands", tr: "Solomon Adaları", fr: "Îles Salomon" } },
  { id: "162", name: { en: "Somalia", tr: "Somali", fr: "Somalie" } },
  { id: "163", name: { en: "South Africa", tr: "Güney Afrika", fr: "Afrique du Sud" } },
  { id: "164", name: { en: "South Korea", tr: "Güney Kore", fr: "Corée du Sud" } },
  { id: "165", name: { en: "South Sudan", tr: "Güney Sudan", fr: "Soudan du Sud" } },
  { id: "166", name: { en: "Spain", tr: "İspanya", fr: "Espagne" } },
  { id: "167", name: { en: "Sri Lanka", tr: "Sri Lanka", fr: "Sri Lanka" } },
  { id: "168", name: { en: "Sudan", tr: "Sudan", fr: "Soudan" } },
  { id: "169", name: { en: "Suriname", tr: "Surinam", fr: "Suriname" } },
  { id: "170", name: { en: "Sweden", tr: "İsveç", fr: "Suède" } },
  { id: "171", name: { en: "Switzerland", tr: "İsviçre", fr: "Suisse" } },
  { id: "172", name: { en: "Syria", tr: "Suriye", fr: "Syrie" } },
  { id: "173", name: { en: "Taiwan", tr: "Tayvan", fr: "Taïwan" } },
  { id: "174", name: { en: "Tajikistan", tr: "Tacikistan", fr: "Tadjikistan" } },
  { id: "175", name: { en: "Tanzania", tr: "Tanzanya", fr: "Tanzanie" } },
  { id: "176", name: { en: "Thailand", tr: "Tayland", fr: "Thaïlande" } },
  { id: "177", name: { en: "Togo", tr: "Togo", fr: "Togo" } },
  { id: "178", name: { en: "Tonga", tr: "Tonga", fr: "Tonga" } },
  { id: "179", name: { en: "Trinidad and Tobago", tr: "Trinidad ve Tobago", fr: "Trinité-et-Tobago" } },
  { id: "180", name: { en: "Tunisia", tr: "Tunus", fr: "Tunisie" } },
  { id: "181", name: { en: "Turkey", tr: "Türkiye", fr: "Turquie" } },
  { id: "182", name: { en: "Turkmenistan", tr: "Türkmenistan", fr: "Turkménistan" } },
  { id: "183", name: { en: "Tuvalu", tr: "Tuvalu", fr: "Tuvalu" } },
  { id: "184", name: { en: "Uganda", tr: "Uganda", fr: "Ouganda" } },
  { id: "185", name: { en: "Ukraine", tr: "Ukrayna", fr: "Ukraine" } },
  { id: "186", name: { en: "United Arab Emirates", tr: "Birleşik Arap Emirlikleri", fr: "Émirats arabes unis" } },
  { id: "187", name: { en: "United Kingdom", tr: "Birleşik Krallık", fr: "Royaume-Uni" } },
  { id: "188", name: { en: "United States", tr: "Amerika Birleşik Devletleri", fr: "États-Unis" } },
  { id: "189", name: { en: "Uruguay", tr: "Uruguay", fr: "Uruguay" } },
  { id: "190", name: { en: "Uzbekistan", tr: "Özbekistan", fr: "Ouzbékistan" } },
  { id: "191", name: { en: "Vanuatu", tr: "Vanuatu", fr: "Vanuatu" } },
  { id: "192", name: { en: "Vatican City", tr: "Vatikan", fr: "Vatican" } },
  { id: "193", name: { en: "Venezuela", tr: "Venezuela", fr: "Venezuela" } },
  { id: "194", name: { en: "Vietnam", tr: "Vietnam", fr: "Vietnam" } },
];
