// Phone country-code dataset. Mirrors panel `Web/src/utils/countries.js`.
// `pattern` validates digits-only national portion, `maxLength` caps it.

export interface PhoneCountry {
  id: string;
  name: string;
  phoneCode: string;
  pattern: RegExp;
  maxLength: number;
}

const TABLE: Record<string, Omit<PhoneCountry, 'id'>> = {
  AF: { name: 'Afghanistan', phoneCode: '+93', pattern: /^\d{9}$/, maxLength: 9 },
  AL: { name: 'Albania', phoneCode: '+355', pattern: /^\d{8,9}$/, maxLength: 9 },
  DZ: { name: 'Algeria', phoneCode: '+213', pattern: /^\d{9}$/, maxLength: 9 },
  AD: { name: 'Andorra', phoneCode: '+376', pattern: /^\d{6}$/, maxLength: 6 },
  AO: { name: 'Angola', phoneCode: '+244', pattern: /^\d{9}$/, maxLength: 9 },
  AR: { name: 'Argentina', phoneCode: '+54', pattern: /^\d{10,11}$/, maxLength: 11 },
  AM: { name: 'Armenia', phoneCode: '+374', pattern: /^\d{8}$/, maxLength: 8 },
  AW: { name: 'Aruba', phoneCode: '+297', pattern: /^\d{7}$/, maxLength: 7 },
  AU: { name: 'Australia', phoneCode: '+61', pattern: /^\d{9}$/, maxLength: 9 },
  AT: { name: 'Austria', phoneCode: '+43', pattern: /^\d{10,11}$/, maxLength: 11 },
  AZ: { name: 'Azerbaijan', phoneCode: '+994', pattern: /^\d{9}$/, maxLength: 9 },
  BH: { name: 'Bahrain', phoneCode: '+973', pattern: /^\d{8}$/, maxLength: 8 },
  BD: { name: 'Bangladesh', phoneCode: '+880', pattern: /^\d{10}$/, maxLength: 10 },
  BY: { name: 'Belarus', phoneCode: '+375', pattern: /^\d{9}$/, maxLength: 9 },
  BE: { name: 'Belgium', phoneCode: '+32', pattern: /^\d{8,9}$/, maxLength: 9 },
  BZ: { name: 'Belize', phoneCode: '+501', pattern: /^\d{7}$/, maxLength: 7 },
  BJ: { name: 'Benin', phoneCode: '+229', pattern: /^\d{8}$/, maxLength: 8 },
  BT: { name: 'Bhutan', phoneCode: '+975', pattern: /^\d{8}$/, maxLength: 8 },
  BO: { name: 'Bolivia', phoneCode: '+591', pattern: /^\d{8}$/, maxLength: 8 },
  BA: { name: 'Bosnia and Herzegovina', phoneCode: '+387', pattern: /^\d{8}$/, maxLength: 8 },
  BW: { name: 'Botswana', phoneCode: '+267', pattern: /^\d{7}$/, maxLength: 7 },
  BR: { name: 'Brazil', phoneCode: '+55', pattern: /^\d{10,11}$/, maxLength: 11 },
  BN: { name: 'Brunei Darussalam', phoneCode: '+673', pattern: /^\d{7}$/, maxLength: 7 },
  BG: { name: 'Bulgaria', phoneCode: '+359', pattern: /^\d{8,9}$/, maxLength: 9 },
  BF: { name: 'Burkina Faso', phoneCode: '+226', pattern: /^\d{8}$/, maxLength: 8 },
  BI: { name: 'Burundi', phoneCode: '+257', pattern: /^\d{8}$/, maxLength: 8 },
  KH: { name: 'Cambodia', phoneCode: '+855', pattern: /^\d{8,9}$/, maxLength: 9 },
  CM: { name: 'Cameroon', phoneCode: '+237', pattern: /^\d{8}$/, maxLength: 8 },
  CA: { name: 'Canada', phoneCode: '+1', pattern: /^\d{10}$/, maxLength: 10 },
  CV: { name: 'Cape Verde', phoneCode: '+238', pattern: /^\d{7}$/, maxLength: 7 },
  CF: { name: 'Central African Republic', phoneCode: '+236', pattern: /^\d{8}$/, maxLength: 8 },
  TD: { name: 'Chad', phoneCode: '+235', pattern: /^\d{8}$/, maxLength: 8 },
  CL: { name: 'Chile', phoneCode: '+56', pattern: /^\d{9}$/, maxLength: 9 },
  CN: { name: 'China', phoneCode: '+86', pattern: /^\d{11}$/, maxLength: 11 },
  CO: { name: 'Colombia', phoneCode: '+57', pattern: /^\d{10}$/, maxLength: 10 },
  KM: { name: 'Comoros', phoneCode: '+269', pattern: /^\d{7}$/, maxLength: 7 },
  CG: { name: 'Congo', phoneCode: '+242', pattern: /^\d{9}$/, maxLength: 9 },
  CD: { name: 'Congo (Democratic Republic of the)', phoneCode: '+243', pattern: /^\d{9}$/, maxLength: 9 },
  CK: { name: 'Cook Islands', phoneCode: '+682', pattern: /^\d{5}$/, maxLength: 5 },
  CR: { name: 'Costa Rica', phoneCode: '+506', pattern: /^\d{8}$/, maxLength: 8 },
  CI: { name: "Côte d'Ivoire", phoneCode: '+225', pattern: /^\d{8}$/, maxLength: 8 },
  HR: { name: 'Croatia', phoneCode: '+385', pattern: /^\d{8,9}$/, maxLength: 9 },
  CU: { name: 'Cuba', phoneCode: '+53', pattern: /^\d{8}$/, maxLength: 8 },
  CW: { name: 'Curaçao', phoneCode: '+599', pattern: /^\d{7}$/, maxLength: 7 },
  CY: { name: 'Cyprus', phoneCode: '+357', pattern: /^\d{8}$/, maxLength: 8 },
  CZ: { name: 'Czech Republic', phoneCode: '+420', pattern: /^\d{9}$/, maxLength: 9 },
  DK: { name: 'Denmark', phoneCode: '+45', pattern: /^\d{8}$/, maxLength: 8 },
  DJ: { name: 'Djibouti', phoneCode: '+253', pattern: /^\d{8}$/, maxLength: 8 },
  EC: { name: 'Ecuador', phoneCode: '+593', pattern: /^\d{8,9}$/, maxLength: 9 },
  EG: { name: 'Egypt', phoneCode: '+20', pattern: /^\d{10}$/, maxLength: 10 },
  SV: { name: 'El Salvador', phoneCode: '+503', pattern: /^\d{8}$/, maxLength: 8 },
  GQ: { name: 'Equatorial Guinea', phoneCode: '+240', pattern: /^\d{9}$/, maxLength: 9 },
  ER: { name: 'Eritrea', phoneCode: '+291', pattern: /^\d{7}$/, maxLength: 7 },
  EE: { name: 'Estonia', phoneCode: '+372', pattern: /^\d{7,8}$/, maxLength: 8 },
  SZ: { name: 'Eswatini', phoneCode: '+268', pattern: /^\d{7}$/, maxLength: 7 },
  ET: { name: 'Ethiopia', phoneCode: '+251', pattern: /^\d{9}$/, maxLength: 9 },
  FK: { name: 'Falkland Islands', phoneCode: '+500', pattern: /^\d{5}$/, maxLength: 5 },
  FO: { name: 'Faroe Islands', phoneCode: '+298', pattern: /^\d{6}$/, maxLength: 6 },
  FJ: { name: 'Fiji', phoneCode: '+679', pattern: /^\d{7}$/, maxLength: 7 },
  FI: { name: 'Finland', phoneCode: '+358', pattern: /^\d{9}$/, maxLength: 9 },
  FR: { name: 'France', phoneCode: '+33', pattern: /^\d{9}$/, maxLength: 9 },
  PF: { name: 'French Polynesia', phoneCode: '+689', pattern: /^\d{6}$/, maxLength: 6 },
  GA: { name: 'Gabon', phoneCode: '+241', pattern: /^\d{7}$/, maxLength: 7 },
  GM: { name: 'Gambia', phoneCode: '+220', pattern: /^\d{7}$/, maxLength: 7 },
  GE: { name: 'Georgia', phoneCode: '+995', pattern: /^\d{9}$/, maxLength: 9 },
  DE: { name: 'Germany', phoneCode: '+49', pattern: /^\d{10,11}$/, maxLength: 11 },
  GH: { name: 'Ghana', phoneCode: '+233', pattern: /^\d{9}$/, maxLength: 9 },
  GI: { name: 'Gibraltar', phoneCode: '+350', pattern: /^\d{8}$/, maxLength: 8 },
  GR: { name: 'Greece', phoneCode: '+30', pattern: /^\d{10}$/, maxLength: 10 },
  GL: { name: 'Greenland', phoneCode: '+299', pattern: /^\d{6}$/, maxLength: 6 },
  GT: { name: 'Guatemala', phoneCode: '+502', pattern: /^\d{8}$/, maxLength: 8 },
  GN: { name: 'Guinea', phoneCode: '+224', pattern: /^\d{8,9}$/, maxLength: 9 },
  GW: { name: 'Guinea-Bissau', phoneCode: '+245', pattern: /^\d{7}$/, maxLength: 7 },
  GY: { name: 'Guyana', phoneCode: '+592', pattern: /^\d{7}$/, maxLength: 7 },
  HT: { name: 'Haiti', phoneCode: '+509', pattern: /^\d{8}$/, maxLength: 8 },
  HN: { name: 'Honduras', phoneCode: '+504', pattern: /^\d{8}$/, maxLength: 8 },
  HU: { name: 'Hungary', phoneCode: '+36', pattern: /^\d{8,9}$/, maxLength: 9 },
  IS: { name: 'Iceland', phoneCode: '+354', pattern: /^\d{7}$/, maxLength: 7 },
  IN: { name: 'India', phoneCode: '+91', pattern: /^\d{10}$/, maxLength: 10 },
  ID: { name: 'Indonesia', phoneCode: '+62', pattern: /^\d{9,12}$/, maxLength: 12 },
  IR: { name: 'Iran', phoneCode: '+98', pattern: /^\d{10}$/, maxLength: 10 },
  IQ: { name: 'Iraq', phoneCode: '+964', pattern: /^\d{10}$/, maxLength: 10 },
  IE: { name: 'Ireland', phoneCode: '+353', pattern: /^\d{9}$/, maxLength: 9 },
  IL: { name: 'Israel', phoneCode: '+972', pattern: /^\d{9}$/, maxLength: 9 },
  IT: { name: 'Italy', phoneCode: '+39', pattern: /^\d{9,10}$/, maxLength: 10 },
  JP: { name: 'Japan', phoneCode: '+81', pattern: /^\d{10,11}$/, maxLength: 11 },
  JO: { name: 'Jordan', phoneCode: '+962', pattern: /^\d{9}$/, maxLength: 9 },
  KZ: { name: 'Kazakhstan', phoneCode: '+7', pattern: /^\d{10}$/, maxLength: 10 },
  KE: { name: 'Kenya', phoneCode: '+254', pattern: /^\d{9}$/, maxLength: 9 },
  KI: { name: 'Kiribati', phoneCode: '+686', pattern: /^\d{5}$/, maxLength: 5 },
  KW: { name: 'Kuwait', phoneCode: '+965', pattern: /^\d{8}$/, maxLength: 8 },
  KG: { name: 'Kyrgyzstan', phoneCode: '+996', pattern: /^\d{9}$/, maxLength: 9 },
  LA: { name: 'Laos', phoneCode: '+856', pattern: /^\d{8}$/, maxLength: 8 },
  LV: { name: 'Latvia', phoneCode: '+371', pattern: /^\d{8}$/, maxLength: 8 },
  LB: { name: 'Lebanon', phoneCode: '+961', pattern: /^\d{7,8}$/, maxLength: 8 },
  LS: { name: 'Lesotho', phoneCode: '+266', pattern: /^\d{8}$/, maxLength: 8 },
  LR: { name: 'Liberia', phoneCode: '+231', pattern: /^\d{7,8}$/, maxLength: 8 },
  LY: { name: 'Libya', phoneCode: '+218', pattern: /^\d{9}$/, maxLength: 9 },
  LI: { name: 'Liechtenstein', phoneCode: '+423', pattern: /^\d{7}$/, maxLength: 7 },
  LT: { name: 'Lithuania', phoneCode: '+370', pattern: /^\d{8}$/, maxLength: 8 },
  LU: { name: 'Luxembourg', phoneCode: '+352', pattern: /^\d{9}$/, maxLength: 9 },
  MO: { name: 'Macao', phoneCode: '+853', pattern: /^\d{8}$/, maxLength: 8 },
  MK: { name: 'North Macedonia', phoneCode: '+389', pattern: /^\d{8}$/, maxLength: 8 },
  MG: { name: 'Madagascar', phoneCode: '+261', pattern: /^\d{9}$/, maxLength: 9 },
  MW: { name: 'Malawi', phoneCode: '+265', pattern: /^\d{7,9}$/, maxLength: 9 },
  MY: { name: 'Malaysia', phoneCode: '+60', pattern: /^\d{9,10}$/, maxLength: 10 },
  MV: { name: 'Maldives', phoneCode: '+960', pattern: /^\d{7}$/, maxLength: 7 },
  ML: { name: 'Mali', phoneCode: '+223', pattern: /^\d{8}$/, maxLength: 8 },
  MT: { name: 'Malta', phoneCode: '+356', pattern: /^\d{8}$/, maxLength: 8 },
  MH: { name: 'Marshall Islands', phoneCode: '+692', pattern: /^\d{7}$/, maxLength: 7 },
  MQ: { name: 'Martinique', phoneCode: '+596', pattern: /^\d{9}$/, maxLength: 9 },
  MR: { name: 'Mauritania', phoneCode: '+222', pattern: /^\d{8}$/, maxLength: 8 },
  MU: { name: 'Mauritius', phoneCode: '+230', pattern: /^\d{7,8}$/, maxLength: 8 },
  YT: { name: 'Mayotte', phoneCode: '+262', pattern: /^\d{9}$/, maxLength: 9 },
  MX: { name: 'Mexico', phoneCode: '+52', pattern: /^\d{10}$/, maxLength: 10 },
  FM: { name: 'Micronesia', phoneCode: '+691', pattern: /^\d{7}$/, maxLength: 7 },
  MD: { name: 'Moldova', phoneCode: '+373', pattern: /^\d{8}$/, maxLength: 8 },
  MC: { name: 'Monaco', phoneCode: '+377', pattern: /^\d{8}$/, maxLength: 8 },
  MN: { name: 'Mongolia', phoneCode: '+976', pattern: /^\d{8}$/, maxLength: 8 },
  ME: { name: 'Montenegro', phoneCode: '+382', pattern: /^\d{8}$/, maxLength: 8 },
  MA: { name: 'Morocco', phoneCode: '+212', pattern: /^\d{9}$/, maxLength: 9 },
  MZ: { name: 'Mozambique', phoneCode: '+258', pattern: /^\d{9}$/, maxLength: 9 },
  MM: { name: 'Myanmar', phoneCode: '+95', pattern: /^\d{8,10}$/, maxLength: 10 },
  NA: { name: 'Namibia', phoneCode: '+264', pattern: /^\d{7}$/, maxLength: 7 },
  NR: { name: 'Nauru', phoneCode: '+674', pattern: /^\d{7}$/, maxLength: 7 },
  NP: { name: 'Nepal', phoneCode: '+977', pattern: /^\d{10}$/, maxLength: 10 },
  NL: { name: 'Netherlands', phoneCode: '+31', pattern: /^\d{9}$/, maxLength: 9 },
  NC: { name: 'New Caledonia', phoneCode: '+687', pattern: /^\d{6}$/, maxLength: 6 },
  NZ: { name: 'New Zealand', phoneCode: '+64', pattern: /^\d{8,9}$/, maxLength: 9 },
  NI: { name: 'Nicaragua', phoneCode: '+505', pattern: /^\d{8}$/, maxLength: 8 },
  NE: { name: 'Niger', phoneCode: '+227', pattern: /^\d{8}$/, maxLength: 8 },
  NG: { name: 'Nigeria', phoneCode: '+234', pattern: /^\d{10}$/, maxLength: 10 },
  KP: { name: 'North Korea', phoneCode: '+850', pattern: /^\d{9}$/, maxLength: 9 },
  NO: { name: 'Norway', phoneCode: '+47', pattern: /^\d{8}$/, maxLength: 8 },
  OM: { name: 'Oman', phoneCode: '+968', pattern: /^\d{8}$/, maxLength: 8 },
  PK: { name: 'Pakistan', phoneCode: '+92', pattern: /^\d{10}$/, maxLength: 10 },
  PW: { name: 'Palau', phoneCode: '+680', pattern: /^\d{7}$/, maxLength: 7 },
  PA: { name: 'Panama', phoneCode: '+507', pattern: /^\d{8}$/, maxLength: 8 },
  PG: { name: 'Papua New Guinea', phoneCode: '+675', pattern: /^\d{7}$/, maxLength: 7 },
  PY: { name: 'Paraguay', phoneCode: '+595', pattern: /^\d{9}$/, maxLength: 9 },
  PE: { name: 'Peru', phoneCode: '+51', pattern: /^\d{9}$/, maxLength: 9 },
  PH: { name: 'Philippines', phoneCode: '+63', pattern: /^\d{10}$/, maxLength: 10 },
  PL: { name: 'Poland', phoneCode: '+48', pattern: /^\d{9}$/, maxLength: 9 },
  PT: { name: 'Portugal', phoneCode: '+351', pattern: /^\d{9}$/, maxLength: 9 },
  QA: { name: 'Qatar', phoneCode: '+974', pattern: /^\d{8}$/, maxLength: 8 },
  RE: { name: 'Réunion', phoneCode: '+262', pattern: /^\d{9}$/, maxLength: 9 },
  RO: { name: 'Romania', phoneCode: '+40', pattern: /^\d{9}$/, maxLength: 9 },
  RU: { name: 'Russia', phoneCode: '+7', pattern: /^\d{10}$/, maxLength: 10 },
  RW: { name: 'Rwanda', phoneCode: '+250', pattern: /^\d{9}$/, maxLength: 9 },
  BL: { name: 'Saint Barthélemy', phoneCode: '+590', pattern: /^\d{9}$/, maxLength: 9 },
  SH: { name: 'Saint Helena', phoneCode: '+290', pattern: /^\d{4}$/, maxLength: 4 },
  MF: { name: 'Saint Martin', phoneCode: '+590', pattern: /^\d{9}$/, maxLength: 9 },
  PM: { name: 'Saint Pierre and Miquelon', phoneCode: '+508', pattern: /^\d{6}$/, maxLength: 6 },
  WS: { name: 'Samoa', phoneCode: '+685', pattern: /^\d{5,7}$/, maxLength: 7 },
  SM: { name: 'San Marino', phoneCode: '+378', pattern: /^\d{8}$/, maxLength: 8 },
  SA: { name: 'Saudi Arabia', phoneCode: '+966', pattern: /^\d{9}$/, maxLength: 9 },
  SN: { name: 'Senegal', phoneCode: '+221', pattern: /^\d{9}$/, maxLength: 9 },
  RS: { name: 'Serbia', phoneCode: '+381', pattern: /^\d{8,9}$/, maxLength: 9 },
  SC: { name: 'Seychelles', phoneCode: '+248', pattern: /^\d{7}$/, maxLength: 7 },
  SL: { name: 'Sierra Leone', phoneCode: '+232', pattern: /^\d{8}$/, maxLength: 8 },
  SG: { name: 'Singapore', phoneCode: '+65', pattern: /^\d{8}$/, maxLength: 8 },
  SK: { name: 'Slovakia', phoneCode: '+421', pattern: /^\d{9}$/, maxLength: 9 },
  SI: { name: 'Slovenia', phoneCode: '+386', pattern: /^\d{8}$/, maxLength: 8 },
  SO: { name: 'Somalia', phoneCode: '+252', pattern: /^\d{7,8}$/, maxLength: 8 },
  ZA: { name: 'South Africa', phoneCode: '+27', pattern: /^\d{9}$/, maxLength: 9 },
  KR: { name: 'South Korea', phoneCode: '+82', pattern: /^\d{10,11}$/, maxLength: 11 },
  ES: { name: 'Spain', phoneCode: '+34', pattern: /^\d{9}$/, maxLength: 9 },
  LK: { name: 'Sri Lanka', phoneCode: '+94', pattern: /^\d{9}$/, maxLength: 9 },
  SD: { name: 'Sudan', phoneCode: '+249', pattern: /^\d{9}$/, maxLength: 9 },
  SR: { name: 'Suriname', phoneCode: '+597', pattern: /^\d{6,7}$/, maxLength: 7 },
  SJ: { name: 'Svalbard and Jan Mayen', phoneCode: '+47', pattern: /^\d{8}$/, maxLength: 8 },
  SE: { name: 'Sweden', phoneCode: '+46', pattern: /^\d{9}$/, maxLength: 9 },
  CH: { name: 'Switzerland', phoneCode: '+41', pattern: /^\d{9}$/, maxLength: 9 },
  SY: { name: 'Syrian Arab Republic', phoneCode: '+963', pattern: /^\d{9}$/, maxLength: 9 },
  TW: { name: 'Taiwan', phoneCode: '+886', pattern: /^\d{9}$/, maxLength: 9 },
  TJ: { name: 'Tajikistan', phoneCode: '+992', pattern: /^\d{9}$/, maxLength: 9 },
  TZ: { name: 'Tanzania', phoneCode: '+255', pattern: /^\d{9}$/, maxLength: 9 },
  TH: { name: 'Thailand', phoneCode: '+66', pattern: /^\d{9}$/, maxLength: 9 },
  TL: { name: 'Timor-Leste', phoneCode: '+670', pattern: /^\d{7}$/, maxLength: 7 },
  TG: { name: 'Togo', phoneCode: '+228', pattern: /^\d{8}$/, maxLength: 8 },
  TO: { name: 'Tonga', phoneCode: '+676', pattern: /^\d{5}$/, maxLength: 5 },
  TN: { name: 'Tunisia', phoneCode: '+216', pattern: /^\d{8}$/, maxLength: 8 },
  TR: { name: 'Turkiye', phoneCode: '+90', pattern: /^\d{10}$/, maxLength: 10 },
  TM: { name: 'Turkmenistan', phoneCode: '+993', pattern: /^\d{8}$/, maxLength: 8 },
  TV: { name: 'Tuvalu', phoneCode: '+688', pattern: /^\d{5}$/, maxLength: 5 },
  UG: { name: 'Uganda', phoneCode: '+256', pattern: /^\d{9}$/, maxLength: 9 },
  UA: { name: 'Ukraine', phoneCode: '+380', pattern: /^\d{9}$/, maxLength: 9 },
  AE: { name: 'United Arab Emirates', phoneCode: '+971', pattern: /^\d{9}$/, maxLength: 9 },
  GB: { name: 'United Kingdom', phoneCode: '+44', pattern: /^\d{10}$/, maxLength: 10 },
  US: { name: 'United States', phoneCode: '+1', pattern: /^\d{10}$/, maxLength: 10 },
  UY: { name: 'Uruguay', phoneCode: '+598', pattern: /^\d{8}$/, maxLength: 8 },
  UZ: { name: 'Uzbekistan', phoneCode: '+998', pattern: /^\d{9}$/, maxLength: 9 },
  VU: { name: 'Vanuatu', phoneCode: '+678', pattern: /^\d{5,7}$/, maxLength: 7 },
  VA: { name: 'Vatican City', phoneCode: '+379', pattern: /^\d{8}$/, maxLength: 8 },
  VE: { name: 'Venezuela', phoneCode: '+58', pattern: /^\d{10}$/, maxLength: 10 },
  VN: { name: 'Vietnam', phoneCode: '+84', pattern: /^\d{9,10}$/, maxLength: 10 },
  WF: { name: 'Wallis and Futuna', phoneCode: '+681', pattern: /^\d{6}$/, maxLength: 6 },
  YE: { name: 'Yemen', phoneCode: '+967', pattern: /^\d{9}$/, maxLength: 9 },
  ZM: { name: 'Zambia', phoneCode: '+260', pattern: /^\d{9}$/, maxLength: 9 },
  ZW: { name: 'Zimbabwe', phoneCode: '+263', pattern: /^\d{9}$/, maxLength: 9 },
};

const PRIORITY = ['TR', 'US', 'CA', 'DE', 'FR', 'GB', 'AE'];

export const PHONE_COUNTRIES: PhoneCountry[] = Object.entries(TABLE)
  .map(([id, data]) => ({ id, ...data }))
  .sort((a, b) => {
    const ia = PRIORITY.indexOf(a.id);
    const ib = PRIORITY.indexOf(b.id);
    if (ia !== -1 && ib !== -1) return ia - ib;
    if (ia !== -1) return -1;
    if (ib !== -1) return 1;
    return a.name.localeCompare(b.name);
  });

export const findPhoneCountry = (id: string): PhoneCountry | undefined =>
  PHONE_COUNTRIES.find((c) => c.id === id);